application: zbtg000001
version: 5
runtime: go
api_version: go1


handlers:

- url: /favicon\.ico
  static_files: /images/favicon.ico
  upload: images/favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /img
  static_dir: img

- url: /(.*)\.html
  static_files: \1.html
  upload: (.*)\.html

- url: /
  static_files: index.html
  upload: index\.html

- url: /.*
  script: _go_app

